# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Demo CI

on:
  push:
    branches: [ demo ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn node ./utils/build.js
      - run: touch dist/.nojekyll
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: dist
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
